version: "3.7"
services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    image: curatedlist-project:back
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine

