# pull official base image
FROM node:14.0.0-alpine

# install build deps required by node-sass
RUN apk add --no-cache python2 make g++ && ln -sf python2 /usr/bin/python

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY . ./

# start app
CMD ["npm", "start"]