# This is a basic workflow to help you get started with Actions

name: Build and Deploy to Cloud Run

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_RUN_PROJECT }}
  RUN_REGION: europe-west1
  SERVICE_NAME: front

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Authenticate to Google Cloud with the service account key
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.RUN_SA_KEY }}

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_RUN_PROJECT }}

    # Build and push image to Artifact Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "$RUN_REGION-docker.pkg.dev/$PROJECT_ID/containers/$SERVICE_NAME:$GITHUB_SHA"
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "$RUN_REGION-docker.pkg.dev/$PROJECT_ID/containers/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
