# This is a basic workflow to help you get started with Actions

name: Build and Deploy to Cloud Run

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_RUN_PROJECT }}
  RUN_REGION: europe-west1
  SERVICE_NAME: front

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: 'curatedlist-project'

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/curatedlist-project/front"
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "front" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/curatedlist-project/front" \
          --platform "managed" \
          --allow-unauthenticated
